# ---------
# Website
# --------
site:
  title: 'Mon site'
  subtitle: 'Mon sous-titre'
  url: http://www.monsite.fr

# ---------
# Client
# --------
administrator:
  firstname: Prénom
  lastname: Nom
  telephone: Téléphone
  telephone_w3c: '+telephone'
  email: mon@email.fr

  location:
    address: ~
    city: ~
    postcode: ~